// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-systems.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_systems_default = defineTool({
  name: "list_key_systems",
  title: "List key systems",
  description: "List the master key systems the signed-in user has access to in their organisation.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("key_systems").select("id,name,reference,status,created_at").order("created_at", { ascending: false });
    if (error) {
      console.error("[mcp] list_key_systems error:", error);
      return { content: [{ type: "text", text: "Something went wrong processing your request" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { systems: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "List orders",
  description: "List recent hardware orders for the signed-in user's organisation.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum orders to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("orders").select("id,po_number,status,total,currency,created_at,customer_po_ref,project_name").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      console.error("[mcp] list_orders error:", error);
      return { content: [{ type: "text", text: "Something went wrong processing your request" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-key-holders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_key_holders_default = defineTool3({
  name: "list_key_holders",
  title: "List key holders",
  description: "List active key holders in the signed-in user's organisation.",
  inputSchema: {
    include_archived: z2.boolean().optional().describe("Set true to also include archived key holders.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("key_holders").select("id,name,email,phone,role,archived_at,created_at").order("name");
    if (!include_archived) q = q.is("archived_at", null);
    const { data, error } = await q;
    if (error) {
      console.error("[mcp] list_key_holders error:", error);
      return { content: [{ type: "text", text: "Something went wrong processing your request" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { key_holders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool4({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in My LOXX user's profile and organisation.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser4(ctx);
    const [{ data: profile }, { data: member }] = await Promise.all([
      supabase.from("profiles").select("id,name,first_name,last_name,email,company,role,is_admin").eq("id", ctx.getUserId()).maybeSingle(),
      supabase.from("org_members").select("org_id,org_role,status").eq("user_id", ctx.getUserId()).eq("status", "active").maybeSingle()
    ]);
    const out = { profile: profile ?? null, membership: member ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(out) }],
      structuredContent: out
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wrblvasfekwaaayorccv";
var mcp_default = defineMcp({
  name: "myloxx-mcp",
  title: "My LOXX",
  version: "0.1.0",
  instructions: "Tools for querying a My LOXX master key platform account. Use `whoami` to confirm the signed-in user, `list_key_systems` to see the organisation's master key systems, `list_orders` to see recent hardware orders, and `list_key_holders` to see people currently holding keys.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_systems_default, list_orders_default, list_key_holders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
